#!/usr/bin/env node

/**
 * 🦞 Lobster AI - Guided Setup Wizard
 * Interactive command-line setup for all integrations
 */

const fs = require('fs');
const path = require('path');
const inquirer = require('inquirer');
const chalk = require('chalk');
const ora = require('ora');
const axios = require('axios');

const envPath = path.join(__dirname, '..', '.env');
const examplePath = path.join(__dirname, '..', '.env.example');

class SetupWizard {
  constructor() {
    this.config = {};
    this.loadExisting();
  }

  /**
   * Load existing .env file
   */
  loadExisting() {
    if (fs.existsSync(envPath)) {
      const content = fs.readFileSync(envPath, 'utf-8');
      const lines = content.split('\n');
      lines.forEach(line => {
        const [key, value] = line.split('=');
        if (key && !key.startsWith('#')) {
          this.config[key.trim()] = value ? value.trim() : '';
        }
      });
    }
  }

  /**
   * Save configuration to .env
   */
  saveConfig() {
    const lines = [];
    lines.push('# 🦞 Lobster AI Configuration');
    lines.push('# Generated by setup wizard\n');

    // Core settings
    lines.push('# Core Settings');
    lines.push(`PORT=${this.config.PORT || 3000}`);
    lines.push(`NODE_ENV=${this.config.NODE_ENV || 'development'}`);
    lines.push(`LOG_LEVEL=${this.config.LOG_LEVEL || 'info'}\n`);

    // LLM Configuration
    lines.push('# LLM Configuration');
    lines.push(`LLM_PROVIDER=${this.config.LLM_PROVIDER || 'ollama'}`);
    lines.push(`OLLAMA_URL=${this.config.OLLAMA_URL || 'http://localhost:11434'}`);
    lines.push(`OLLAMA_MODEL=${this.config.OLLAMA_MODEL || 'mistral'}`);
    lines.push(`OLLAMA_TIMEOUT=${this.config.OLLAMA_TIMEOUT || 30000}\n`);

    // Voice Configuration
    lines.push('# Voice Configuration');
    lines.push(`VOICE_ENABLED=${this.config.VOICE_ENABLED !== 'false'}`);
    lines.push(`WHISPER_MODEL=${this.config.WHISPER_MODEL || 'base'}`);
    lines.push(`TTS_PROVIDER=${this.config.TTS_PROVIDER || 'local'}\n`);

    // Database
    lines.push('# Database');
    lines.push(`DB_PATH=${this.config.DB_PATH || './data/lobster.db'}\n`);

    // Chat Integrations
    lines.push('# Chat Integrations');
    lines.push(`TELEGRAM_ENABLED=${this.config.TELEGRAM_ENABLED || 'false'}`);
    lines.push(`TELEGRAM_TOKEN=${this.config.TELEGRAM_TOKEN || ''}`);
    lines.push(`DISCORD_ENABLED=${this.config.DISCORD_ENABLED || 'false'}`);
    lines.push(`DISCORD_TOKEN=${this.config.DISCORD_TOKEN || ''}`);
    lines.push(`SLACK_ENABLED=${this.config.SLACK_ENABLED || 'false'}`);
    lines.push(`SLACK_BOT_TOKEN=${this.config.SLACK_BOT_TOKEN || ''}`);
    lines.push(`SLACK_SIGNING_SECRET=${this.config.SLACK_SIGNING_SECRET || ''}`);
    lines.push(`WHATSAPP_ENABLED=${this.config.WHATSAPP_ENABLED || 'false'}`);
    lines.push(`WHATSAPP_SESSION_PATH=${this.config.WHATSAPP_SESSION_PATH || './data/whatsapp-session'}\n`);

    // Privacy & Security
    lines.push('# Privacy & Security');
    lines.push(`ENABLE_ANALYTICS=${this.config.ENABLE_ANALYTICS || 'false'}`);
    lines.push(`ENABLE_TELEMETRY=${this.config.ENABLE_TELEMETRY || 'false'}`);
    lines.push(`ALLOW_REMOTE_ACCESS=${this.config.ALLOW_REMOTE_ACCESS || 'false'}`);
    lines.push(`MAX_MESSAGE_HISTORY=${this.config.MAX_MESSAGE_HISTORY || 1000}\n`);

    // Personality
    lines.push('# Personality');
    lines.push(`PERSONALITY_NAME=${this.config.PERSONALITY_NAME || 'Lobster'}`);
    lines.push(`PERSONALITY_QUIRKY_MODE=${this.config.PERSONALITY_QUIRKY_MODE !== 'false'}`);

    fs.writeFileSync(envPath, lines.join('\n'));
  }

  /**
   * Main setup flow
   */
  async run() {
    console.clear();
    console.log(chalk.cyan('\n🦞 Welcome to Lobster AI Setup!\n'));
    console.log(chalk.gray('Let\'s get your personal AI assistant up and running.\n'));

    // LLM Setup
    await this.setupLLM();

    // Chat Integrations
    await this.setupChatIntegrations();

    // Personality
    await this.setupPersonality();

    // Test connection
    await this.testConnection();

    // Save and finish
    this.saveConfig();

    console.log(chalk.green('\n✅ Setup complete!\n'));
    console.log(chalk.cyan('Next steps:\n'));
    console.log(chalk.gray('  1. npm install       - Install dependencies'));
    console.log(chalk.gray('  2. npm start         - Start Lobster AI'));
    console.log(chalk.gray('  3. Send a message!   - Chat with your assistant\n'));
  }

  /**
   * Setup LLM Configuration
   */
  async setupLLM() {
    console.log(chalk.blue('\n🧠 LLM Configuration\n'));

    const answers = await inquirer.prompt([\n      {\n        type: 'list',\n        name: 'llmProvider',\n        message: 'Which LLM would you like to use?',\n        choices: [\n          { name: 'Ollama (recommended)', value: 'ollama' },\n          { name: 'LM Studio', value: 'lmstudio' }\n        ],\n        default: this.config.LLM_PROVIDER || 'ollama'\n      }\n    ]);\n\n    this.config.LLM_PROVIDER = answers.llmProvider;\n\n    if (answers.llmProvider === 'ollama') {\n      const ollamaAnswers = await inquirer.prompt([\n        {\n          type: 'input',\n          name: 'ollamaUrl',\n          message: 'Ollama URL:',\n          default: this.config.OLLAMA_URL || 'http://localhost:11434'\n        },\n        {\n          type: 'input',\n          name: 'ollamaModel',\n          message: 'Ollama Model (e.g., mistral, neural-chat, llama2):',\n          default: this.config.OLLAMA_MODEL || 'mistral'\n        }\n      ]);\n\n      this.config.OLLAMA_URL = ollamaAnswers.ollamaUrl;\n      this.config.OLLAMA_MODEL = ollamaAnswers.ollamaModel;\n    } else {\n      const lmstudioAnswers = await inquirer.prompt([\n        {\n          type: 'input',\n          name: 'lmstudioUrl',\n          message: 'LM Studio URL:',\n          default: this.config.LMSTUDIO_URL || 'http://localhost:1234'\n        }\n      ]);\n\n      this.config.LMSTUDIO_URL = lmstudioAnswers.lmstudioUrl;\n    }\n  }\n\n  /**\n   * Setup Chat Integrations\n   */\n  async setupChatIntegrations() {\n    console.log(chalk.blue('\n💬 Chat Integrations\n'));\n\n    const integrations = await inquirer.prompt([\n      {\n        type: 'confirm',\n        name: 'telegram',\n        message: 'Enable Telegram?',\n        default: this.config.TELEGRAM_ENABLED === 'true'\n      },\n      {\n        type: 'confirm',\n        name: 'discord',\n        message: 'Enable Discord?',\n        default: this.config.DISCORD_ENABLED === 'true'\n      },\n      {\n        type: 'confirm',\n        name: 'slack',\n        message: 'Enable Slack?',\n        default: this.config.SLACK_ENABLED === 'true'\n      },\n      {\n        type: 'confirm',\n        name: 'whatsapp',\n        message: 'Enable WhatsApp?',\n        default: this.config.WHATSAPP_ENABLED === 'true'\n      }\n    ]);\n\n    // Get tokens for enabled integrations\n    if (integrations.telegram) {\n      const telegramAnswers = await inquirer.prompt([\n        {\n          type: 'password',\n          name: 'token',\n          message: 'Telegram Bot Token (from @BotFather):',\n          default: this.config.TELEGRAM_TOKEN\n        }\n      ]);\n      this.config.TELEGRAM_ENABLED = 'true';\n      this.config.TELEGRAM_TOKEN = telegramAnswers.token;\n    } else {\n      this.config.TELEGRAM_ENABLED = 'false';\n    }\n\n    if (integrations.discord) {\n      const discordAnswers = await inquirer.prompt([\n        {\n          type: 'password',\n          name: 'token',\n          message: 'Discord Bot Token:',\n          default: this.config.DISCORD_TOKEN\n        }\n      ]);\n      this.config.DISCORD_ENABLED = 'true';\n      this.config.DISCORD_TOKEN = discordAnswers.token;\n    } else {\n      this.config.DISCORD_ENABLED = 'false';\n    }\n\n    if (integrations.slack) {\n      const slackAnswers = await inquirer.prompt([\n        {\n          type: 'password',\n          name: 'botToken',\n          message: 'Slack Bot Token:',\n          default: this.config.SLACK_BOT_TOKEN\n        },\n        {\n          type: 'password',\n          name: 'signingSecret',\n          message: 'Slack Signing Secret:',\n          default: this.config.SLACK_SIGNING_SECRET\n        }\n      ]);\n      this.config.SLACK_ENABLED = 'true';\n      this.config.SLACK_BOT_TOKEN = slackAnswers.botToken;\n      this.config.SLACK_SIGNING_SECRET = slackAnswers.signingSecret;\n    } else {\n      this.config.SLACK_ENABLED = 'false';\n    }\n\n    if (integrations.whatsapp) {\n      this.config.WHATSAPP_ENABLED = 'true';\n      console.log(chalk.yellow('\n⚠️  WhatsApp: Scan QR code when bot starts to authenticate\n'));\n    } else {\n      this.config.WHATSAPP_ENABLED = 'false';\n    }\n  }\n\n  /**\n   * Setup Personality\n   */\n  async setupPersonality() {\n    console.log(chalk.blue('\n🦞 Personality\n'));\n\n    const personalityAnswers = await inquirer.prompt([\n      {\n        type: 'input',\n        name: 'name',\n        message: 'Assistant name:',\n        default: this.config.PERSONALITY_NAME || 'Lobster'\n      },\n      {\n        type: 'confirm',\n        name: 'quirky',\n        message: 'Enable quirky personality mode?',\n        default: this.config.PERSONALITY_QUIRKY_MODE !== 'false'\n      }\n    ]);\n\n    this.config.PERSONALITY_NAME = personalityAnswers.name;\n    this.config.PERSONALITY_QUIRKY_MODE = personalityAnswers.quirky ? 'true' : 'false';\n  }\n\n  /**\n   * Test LLM Connection\n   */\n  async testConnection() {\n    console.log(chalk.blue('\n🧪 Testing Connection\n'));\n\n    const spinner = ora('Testing LLM connection...').start();\n\n    try {\n      const url = this.config.LLM_PROVIDER === 'ollama'\n        ? `${this.config.OLLAMA_URL}/api/tags`\n        : `${this.config.LMSTUDIO_URL}/v1/models`;\n\n      await axios.get(url, { timeout: 5000 });\n      spinner.succeed('✅ LLM connection successful!');\n    } catch (error) {\n      spinner.fail('⚠️  Could not connect to LLM. Make sure it\\'s running.');\n      console.log(chalk.gray(`\\nURL: ${this.config.LLM_PROVIDER === 'ollama' ? this.config.OLLAMA_URL : this.config.LMSTUDIO_URL}`));\n    }\n  }\n}\n\n// Run setup\nif (require.main === module) {\n  const wizard = new SetupWizard();\n  wizard.run().catch(error => {\n    console.error(chalk.red('Setup failed:'), error);\n    process.exit(1);\n  });\n}\n\nmodule.exports = SetupWizard;